# Generated by Django 2.2.16 on 2023-03-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20230330_2053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MenuModel',
        ),
    ]
