# Generated by Django 2.2.16 on 2023-04-01 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menumodel',
            name='slug',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
