# Generated by Django 2.2.16 on 2023-04-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20230402_1247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitemmodel',
            options={'verbose_name': 'Menu Section'},
        ),
        migrations.AlterModelOptions(
            name='menumodel',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
        migrations.AlterField(
            model_name='menuitemmodel',
            name='slug',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
