# Generated by Django 2.2.16 on 2023-04-01 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_menumodel_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('menu_name', models.CharField(max_length=50)),
                ('slug', models.CharField(blank=True, max_length=50)),
                ('url', models.CharField(blank=True, max_length=50)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.MenuItemModel')),
            ],
        ),
        migrations.DeleteModel(
            name='MenuModel',
        ),
    ]
